import type { GeminiSettings } from '../../types/gemini-config'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import dayjs from 'dayjs'
import { ensureDirSync } from 'fs-extra'
import { join } from 'pathe'
import { GEMINI_CONTEXT_FILE, GEMINI_DIR } from '../../constants'
import { ensureI18nInitialized, i18n } from '../../i18n'
import { readGeminiSettings } from './gemini-config-manager'

/**
 * Default GEMINI.md template
 */
const DEFAULT_GEMINI_CONTEXT = `# Gemini CLI Context

**Last Updated**: {{timestamp}}

## Current Configuration

- **Mode**: {{mode}}
- **Provider**: {{providerName}}
{{#if customProvider}}
- **Base URL**: {{customProvider.baseUrl}}
- **Model**: {{customProvider.model}}
- **Wire Protocol**: {{customProvider.wireProtocol}}
{{/if}}
{{#if officialAuth}}
- **Authentication**: {{officialAuth.type}}
{{#if officialAuth.vertexAiProject}}
- **Vertex AI Project**: {{officialAuth.vertexAiProject}}
{{/if}}
{{/if}}

## Enabled Tools

{{#each enabledTools}}
- {{this}}
{{/each}}

## MCP Servers

{{#each mcpServers}}
### {{@key}}
- Command: \`{{this.command}} {{#each this.args}}{{this}} {{/each}}\`
{{#if this.env}}
- Environment Variables:
{{#each this.env}}
  - {{@key}}: \`{{this}}\`
{{/each}}
{{/if}}
{{/each}}

## Custom Commands

{{#each customCommands}}
### /{{@key}}
{{this.prompt}}
{{#if this.model}}
- Model: {{this.model}}
{{/if}}
- Include Context: {{this.includeContext}}
{{/each}}

## Usage Notes

- This file is automatically generated and updated by ZCF
- Manual changes will be preserved unless regenerated
- Use \`zcf gemini config\` to manage your Gemini configuration

## Quick Start

1. **Official Mode (Google Gemini)**:
   \`\`\`bash
   gemini -p "Your prompt here"
   \`\`\`

2. **Custom Provider Mode**:
   - Configuration is managed through ZCF
   - Use \`zcf gemini config\` to switch providers

## Resources

- [Gemini CLI Documentation](https://ai.google.dev/gemini-api/docs/cli)
- [ZCF Documentation](https://github.com/levi-0422/zcf)
`

/**
 * Read GEMINI.md context file
 */
export function readGeminiContext(): string | null {
  if (!existsSync(GEMINI_CONTEXT_FILE)) {
    return null
  }

  try {
    return readFileSync(GEMINI_CONTEXT_FILE, 'utf-8')
  }
  catch (error) {
    ensureI18nInitialized()
    console.error(i18n.t('gemini:context.readError'), error)
    return null
  }
}

/**
 * Write GEMINI.md context file
 */
export function writeGeminiContext(content: string): void {
  ensureDirSync(GEMINI_DIR)

  try {
    writeFileSync(GEMINI_CONTEXT_FILE, content, 'utf-8')
  }
  catch (error) {
    ensureI18nInitialized()
    throw new Error(`${i18n.t('gemini:context.writeError')}: ${error}`)
  }
}

/**
 * Generate GEMINI.md content from settings
 */
export function generateGeminiContext(): string {
  const settings = readGeminiSettings()
  if (!settings) {
    return DEFAULT_GEMINI_CONTEXT.replace('{{timestamp}}', dayjs().format('YYYY-MM-DD HH:mm:ss'))
  }

  const timestamp = dayjs().format('YYYY-MM-DD HH:mm:ss')
  const mode = settings.mode || 'official'
  const providerName = mode === 'official'
    ? 'Google Gemini Official'
    : settings.customProvider?.name || 'Unknown'

  let content = `# Gemini CLI Context

**Last Updated**: ${timestamp}

## Current Configuration

- **Mode**: ${mode}
- **Provider**: ${providerName}
`

  // Add custom provider details
  if (mode === 'custom' && settings.customProvider) {
    content += `- **Base URL**: ${settings.customProvider.baseUrl}
- **Model**: ${settings.customProvider.model || 'Default'}
- **Wire Protocol**: ${settings.customProvider.wireProtocol || 'openai'}
`
  }

  // Add official authentication details
  if (mode === 'official') {
    content += `- **Authentication**: ${settings.authentication.type}
`
    if (settings.authentication.vertexAiProject) {
      content += `- **Vertex AI Project**: ${settings.authentication.vertexAiProject}
`
    }
  }

  // Add enabled tools
  if (settings.tools?.enabled && settings.tools.enabled.length > 0) {
    content += `\n## Enabled Tools

`
    for (const tool of settings.tools.enabled) {
      content += `- ${tool}\n`
    }
  }

  // Add MCP servers
  if (settings.mcpServers && Object.keys(settings.mcpServers).length > 0) {
    content += `\n## MCP Servers

`
    for (const [name, config] of Object.entries(settings.mcpServers)) {
      content += `### ${name}
- Command: \`${config.command}${config.args ? ` ${config.args.join(' ')}` : ''}\`
`
      if (config.env && Object.keys(config.env).length > 0) {
        content += `- Environment Variables:
`
        for (const [key, value] of Object.entries(config.env)) {
          content += `  - ${key}: \`${value}\`\n`
        }
      }
      content += '\n'
    }
  }

  // Add custom commands
  if (settings.customCommands && Object.keys(settings.customCommands).length > 0) {
    content += `## Custom Commands

`
    for (const [name, config] of Object.entries(settings.customCommands)) {
      content += `### /${name}
${config.prompt}
`
      if (config.model) {
        content += `- Model: ${config.model}\n`
      }
      content += `- Include Context: ${config.includeContext ? 'Yes' : 'No'}\n\n`
    }
  }

  // Add usage notes
  content += `\n## Usage Notes

- This file is automatically generated and updated by ZCF
- Manual changes will be preserved unless regenerated
- Use \`zcf gemini config\` to manage your Gemini configuration

## Quick Start

1. **Official Mode (Google Gemini)**:
   \`\`\`bash
   gemini -p "Your prompt here"
   \`\`\`

2. **Custom Provider Mode**:
   - Configuration is managed through ZCF
   - Use \`zcf gemini config\` to switch providers

## Resources

- [Gemini CLI Documentation](https://ai.google.dev/gemini-api/docs/cli)
- [ZCF Documentation](https://github.com/levi-0422/zcf)
`

  return content
}

/**
 * Update GEMINI.md context file based on current settings
 */
export function updateGeminiContext(): void {
  ensureI18nInitialized()

  const content = generateGeminiContext()
  writeGeminiContext(content)

  console.log(i18n.t('gemini:context.updated'))
}

/**
 * Backup GEMINI.md context file
 */
export function backupGeminiContext(): string {
  ensureI18nInitialized()

  const content = readGeminiContext()
  if (!content) {
    throw new Error(i18n.t('gemini:context.noContextToBackup'))
  }

  const timestamp = dayjs().format('YYYY-MM-DD_HH-mm-ss')
  const backupDir = join(GEMINI_DIR, 'backup')
  ensureDirSync(backupDir)

  const backupPath = join(backupDir, `GEMINI.backup.${timestamp}.md`)

  writeFileSync(backupPath, content, 'utf-8')

  return backupPath
}

/**
 * Check if GEMINI.md context file exists
 */
export function isGeminiContextExists(): boolean {
  return existsSync(GEMINI_CONTEXT_FILE)
}

/**
 * Initialize GEMINI.md context file
 */
export function initializeGeminiContext(): void {
  ensureI18nInitialized()

  if (isGeminiContextExists()) {
    console.log(i18n.t('gemini:context.alreadyExists'))
    return
  }

  updateGeminiContext()
  console.log(i18n.t('gemini:context.initialized'))
}

/**
 * Add custom section to GEMINI.md
 */
export function addCustomSection(title: string, content: string): void {
  ensureI18nInitialized()

  let existingContent = readGeminiContext()
  if (!existingContent) {
    existingContent = generateGeminiContext()
  }

  // Add custom section before "Resources" section
  const resourcesIndex = existingContent.indexOf('## Resources')
  if (resourcesIndex !== -1) {
    const customSection = `\n## ${title}\n\n${content}\n`
    existingContent = existingContent.slice(0, resourcesIndex) + customSection + existingContent.slice(resourcesIndex)
  }
  else {
    existingContent += `\n## ${title}\n\n${content}\n`
  }

  writeGeminiContext(existingContent)
  console.log(i18n.t('gemini:context.sectionAdded', { title }))
}

/**
 * Get configuration summary for display
 */
export function getConfigSummary(): string {
  const settings = readGeminiSettings()
  if (!settings) {
    return 'No configuration found'
  }

  const mode = settings.mode || 'official'
  const providerName = mode === 'official'
    ? 'Google Gemini Official'
    : settings.customProvider?.name || 'Unknown'

  let summary = `Mode: ${mode}\nProvider: ${providerName}\n`

  if (mode === 'custom' && settings.customProvider) {
    summary += `Base URL: ${settings.customProvider.baseUrl}\n`
    summary += `Model: ${settings.customProvider.model || 'Default'}\n`
  }

  if (settings.tools?.enabled) {
    summary += `Enabled Tools: ${settings.tools.enabled.length}\n`
  }

  if (settings.mcpServers) {
    summary += `MCP Servers: ${Object.keys(settings.mcpServers).length}\n`
  }

  if (settings.customCommands) {
    summary += `Custom Commands: ${Object.keys(settings.customCommands).length}\n`
  }

  return summary
}
